---
  # Deploy kubeconfig files to all nodes
  - name: Create a copy of admin.conf to config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /etc/kubernetes/config
    become: true

  - name: Copy config keys to all nodes
    copy:
      src: /etc/kubernetes/config
      dest: /root/.kube/
      owner: root
      group: root
    become: true

  - name: Copy token key to all nodes (required for kubeadm join)
    copy:
      src: /tmp/kubeadm_token
      dest: /tmp/kubeadm_token
