---
  # Deploy kubeconfig files to all nodes

  # As copy doesn't use respect become=true, the below is a workaround
  # more info: https://github.com/ansible/ansible/issues/21145
  - name: Set admin.conf chmod bits to 644
    file:
      path: /etc/kubernetes/admin.conf
      mode: '0644'

  - name: Create a copy of admin.conf to config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /etc/kubernetes/config

  - name: Copy config keys to all nodes for root user
    copy:
      src: /etc/kubernetes/config
      dest: /root/.kube/
      owner: root
      group: root

  - name: Copy token key to all nodes (required for kubeadm join)
    copy:
      src: /tmp/kubeadm_token
      dest: /tmp/kubeadm_token
