---
  # Kubernetes installation finalize
  - name: Kubernetes installation finalize
    debug:
      msg:
        - "Finished installing Kubernetes."
        - "Note that it may take a few minutes before all containers are running."
        - ""
        - "Please validate that all containers are 'Running' using:"
        - "kubectl get pods --all-namespaces"
        - ""
        - "Once all containers are running open the Kubernetes Dashboard:"
        - "https://<ip>:{{dashboard_service_port}}"
        - ""
        - "If you have configured 'demo_environment=yes', click 'skip' on K8S sign in page."
#    with_items:
#      -  "{{groups['masternode']}}"


